"""
Provide a connection between anemoi and cascade.

Exposes the `fluent` API for running anemoi models in cascade.
"""

from anemoi.cascade import fluent


try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"

__all__ = ["fluent", "__version__"]
