"""
Provide a connection between anemoi and cascade.

Exposes the `fluent` API for running anemoi models in cascade.
"""

from anemoicascade import fluent
from anemoicascade import serialisation

from cascade.backends import register as register_backend

# from .wrappers.array_list import ArrayFieldList
from .backends.fieldlist import ArrayFieldListBackend

from earthkit.data.sources import array_list
register_backend(array_list.ArrayFieldList, ArrayFieldListBackend)


try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"